/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RentEscrowInterface extends Interface {
    getFunction(nameOrSignature: "amount" | "confirmLease" | "confirmed" | "deadline" | "getAverageRating" | "getNumRatings" | "landlord" | "landlordConfirmed" | "numRatings" | "rateLandlord" | "refund" | "releaseFunds" | "tenant" | "tenantConfirmed" | "totalRating" | "yieldPercent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Confirmed" | "Deposited" | "Rated" | "Refunded" | "Released"): EventFragment;

    encodeFunctionData(functionFragment: 'amount', values?: undefined): string;
encodeFunctionData(functionFragment: 'confirmLease', values?: undefined): string;
encodeFunctionData(functionFragment: 'confirmed', values?: undefined): string;
encodeFunctionData(functionFragment: 'deadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAverageRating', values?: undefined): string;
encodeFunctionData(functionFragment: 'getNumRatings', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlord', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlordConfirmed', values?: undefined): string;
encodeFunctionData(functionFragment: 'numRatings', values?: undefined): string;
encodeFunctionData(functionFragment: 'rateLandlord', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refund', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseFunds', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenant', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenantConfirmed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRating', values?: undefined): string;
encodeFunctionData(functionFragment: 'yieldPercent', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'amount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmLease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAverageRating', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNumRatings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlordConfirmed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'numRatings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rateLandlord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenant', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenantConfirmed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRating', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yieldPercent', data: BytesLike): Result;
  }

  
    export namespace ConfirmedEvent {
      export type InputTuple = [by: AddressLike, tenantConfirmed: boolean, landlordConfirmed: boolean];
      export type OutputTuple = [by: string, tenantConfirmed: boolean, landlordConfirmed: boolean];
      export interface OutputObject {by: string, tenantConfirmed: boolean, landlordConfirmed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [from: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, value: bigint];
      export interface OutputObject {from: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RatedEvent {
      export type InputTuple = [by: AddressLike, score: BigNumberish];
      export type OutputTuple = [by: string, score: bigint];
      export interface OutputObject {by: string, score: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundedEvent {
      export type InputTuple = [value: BigNumberish];
      export type OutputTuple = [value: bigint];
      export interface OutputObject {value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReleasedEvent {
      export type InputTuple = [value: BigNumberish, yield_: BigNumberish];
      export type OutputTuple = [value: bigint, yield_: bigint];
      export interface OutputObject {value: bigint, yield: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RentEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): RentEscrow;
    waitForDeployment(): Promise<this>;

    interface: RentEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    amount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    confirmLease: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    confirmed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    deadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAverageRating: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getNumRatings: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    landlord: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    landlordConfirmed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    numRatings: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rateLandlord: TypedContractMethod<
      [score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    refund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseFunds: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    tenant: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tenantConfirmed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    totalRating: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    yieldPercent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'amount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'confirmLease'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAverageRating'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getNumRatings'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'landlord'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'landlordConfirmed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'numRatings'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rateLandlord'): TypedContractMethod<
      [score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseFunds'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tenant'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tenantConfirmed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalRating'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'yieldPercent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Confirmed'): TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'Rated'): TypedContractEvent<RatedEvent.InputTuple, RatedEvent.OutputTuple, RatedEvent.OutputObject>;
getEvent(key: 'Refunded'): TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
getEvent(key: 'Released'): TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;

    filters: {
      
      'Confirmed(address,bool,bool)': TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
      Confirmed: TypedContractEvent<ConfirmedEvent.InputTuple, ConfirmedEvent.OutputTuple, ConfirmedEvent.OutputObject>;
    

      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'Rated(address,uint256)': TypedContractEvent<RatedEvent.InputTuple, RatedEvent.OutputTuple, RatedEvent.OutputObject>;
      Rated: TypedContractEvent<RatedEvent.InputTuple, RatedEvent.OutputTuple, RatedEvent.OutputObject>;
    

      'Refunded(uint256)': TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
      Refunded: TypedContractEvent<RefundedEvent.InputTuple, RefundedEvent.OutputTuple, RefundedEvent.OutputObject>;
    

      'Released(uint256,uint256)': TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
      Released: TypedContractEvent<ReleasedEvent.InputTuple, ReleasedEvent.OutputTuple, ReleasedEvent.OutputObject>;
    
    };
  }